### ISSUE TITLE
Relocate the overflow menu and the kebab menu in userChrome-ONE-LINER.css to the right corner

### ISSUE THREAD

**Issue by NashifAlam** [datguypiko/Firefox-Mod-Blur#10]
Can you please move the menu buttons from the mid point in userChrome-ONE-LINER.css to the right most side, as found in the default version. The current placement is quite inconvenient to use.

**Comment by datguypiko** [comment]
Not working on oneliner anymore because I need to update it for Proton. Maybe in the future.
