### ISSUE TITLE
min-max-close styling does not work with the theme default in Firefox 122 / Windows 11

### ISSUE THREAD

**Issue by OlinB** [datguypiko/Firefox-Mod-Blur#104]
Starting with Firefox 122 (am running 122.0b1) the close/reduce buttons are above the Firefox menu and extensions as seen here: 
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/45310038/cac08d82-2b75-4f2c-91ea-142f6ac4a44a)

(I've slightly tweaked some things, but not touched padding and margins at all)

**Comment by datguypiko** [comment]
Because the latest version is 121.

The fix https://github.com/datguypiko/Firefox-Mod-Blur/issues/102

**Comment by OlinB** [comment]
Works great! Thanks a lot!
