### ISSUE TITLE
MicaForEveryone but on linux

### ISSUE THREAD

**Issue by LOLZSICKA** [datguypiko/Firefox-Mod-Blur#106]
can you figure out some way to make the top transparent on linux using some alternitave method?
i really like the micaforeveryone theme

**Comment by LOLZSICKA** [comment]
> Distro?
> 
> xorg or wayland?

Sorry for not responding, it takes me an eternity to check emails but i guess ideally a couple different distros? Im on xorg

**Comment by datguypiko** [comment]
Try something like https://github.com/yshui/picom (maybe need [this ](https://store.kde.org/p/1294604/)too) or "blur my shell" extension. And then add my mica files, they should work too. I dont use linux myself so I cant help with anything else.

**Comment by LOLZSICKA** [comment]
K ill try

**Comment by datguypiko** [comment]
Ask if need anything later
