### ISSUE TITLE
dropdown menu item texts covered behind scrollbar

### ISSUE THREAD

**Issue by livingator** [datguypiko/Firefox-Mod-Blur#110]
as described in title i'm getting issue like this below, any fix for it?
![Screenshot_1](https://github.com/datguypiko/Firefox-Mod-Blur/assets/33782176/8817d6d6-bcc9-4956-abc7-407f58c01c5c)

**Comment by datguypiko** [comment]
Remove these lines from userChrome.css or redownload the [file](https://github.com/datguypiko/Firefox-Mod-Blur/blob/master/userChrome.css).
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/678ee981-7bab-411d-b721-c4a0f95353d6)

**Comment by livingator** [comment]
it works, thanks!
