### ISSUE TITLE
Container extension code breaks pinned tabs' style

### ISSUE THREAD

**Issue by yujinlin0224** [datguypiko/Firefox-Mod-Blur#111]
https://github.com/datguypiko/Firefox-Mod-Blur/blob/89f8e6b03c0f6d710a7b68f2eb9a67b6b41130e7/userChrome.css#L1485-L1489
makes background of pinned tabs different to normal tabs, like
![圖片](https://github.com/datguypiko/Firefox-Mod-Blur/assets/11353779/27d0bccd-ac28-441d-8a1e-28866283ef72)
After I remove these codes, pinned tabs become normal
![圖片](https://github.com/datguypiko/Firefox-Mod-Blur/assets/11353779/8209d2cb-5a2e-4791-9aa3-1cd0b5af162d)

**Comment by datguypiko** [comment]
fixed it.
