### ISSUE TITLE
Firefox button behind windows buttons after firefox update

### ISSUE THREAD

**Issue by ryannmahajan** [datguypiko/Firefox-Mod-Blur#112]
Since the Firefox 122 update, the menu button has been hiding behind the windows button

![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/22999944/f04bef3d-e4b3-41a0-b61b-b02a7abe5a9e)

Earlier, the button was just to the left of them. Is there any way to restore it?

**Comment by datguypiko** [comment]
what OS are you using? Looks like this on windows with latest
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/49d21701-a54a-4e17-bd09-9a5157c8ab2f)
