### ISSUE TITLE
Settings for macOS using the Left side MacOS style

### ISSUE THREAD

**Issue by jamesjingyi** [datguypiko/Firefox-Mod-Blur#117]
I wanted to use this in macOS as well as on my Windows machine and the only thing I had to adjust was in the `min-max-close_buttons.css` file (which I selected from the `Left side MacOS style buttons` folder) to adjust the positioning of the close, minimise, and maximise buttons:

`#navigator-toolbox:not([inFullscreen]) #TabsToolbar `
`     .titlebar-buttonbox-container {`
`          visibility: visible !important;`
`          position: absolute !important;`
`          top: 12px !important;`
`          left: 1px !important;`
`          right: unset !important; `
`}`

Just the 12px and 1px to align it nicely - I tried to adjust the whole height of the top bar so I could align it with other windows in macOS but I am not sure of what to change, had a play but couldn't get it to work. Happy to have play if you let me know what to edit!

**Comment by datguypiko** [comment]
You could try lowering --urlbar-toolbar-height or -urlbar-container-height in userchrome on line 382/386. But it depends how much you need it. Some things will break if went lower because of the way it's made.
