### ISSUE TITLE
Inconsistent Icons

### ISSUE THREAD

**Issue by wealstarr** [datguypiko/Firefox-Mod-Blur#118]
Hello,

The thickness of the caption icons (min-max-close) is not consistent with other icons.
![Capture](https://github.com/datguypiko/Firefox-Mod-Blur/assets/26643729/e286ad4d-1cfb-4434-bcfa-1c7cc65e2f35)

Would it be possible to make all other icons consistent with caption icons ? (other icons are way too thick)

Kind regards

**Comment by datguypiko** [comment]
That's how it is by default.

**Comment by wealstarr** [comment]
Hello @datguypiko 

Thank you for the response. Yes, I understand that's the default position but I see some people changed the icons. Is it not possible ?
