### ISSUE TITLE
Changing toolbar order causes weird X closeout artifact

### ISSUE THREAD

**Issue by anthonysgro** [datguypiko/Firefox-Mod-Blur#119]
Ultimately, I am basically trying to get my tabs to show up on the top of the toolbar, but this causes 2 issues.

1. Artifact over X closeout button on the top right
3. Tabs overflow and you cannot add any more, and start colliding with the minimize, maximize, and close out buttons.

Image for issue 1: https://imgur.com/DVYUni9
Image for issue 2: https://imgur.com/mk48mvX

To reproduce this, install as normal and then make the following modification to userChrome.css:

```
/*=====================================================================
====================== T O O L B A R   O R D E R ======================
=======================================================================
Order of Toolbars
  * 0 - top
  * 1 - second from top
  * 2 - bottom */

/* SEARCH BAR TOOLBAR */
#navigator-toolbox #nav-bar {
  order: 1 !important;
}

/* TABS TOOLBAR */
#titlebar {
  order: 0 !important;
}

/* BOOKMARKS TOOLBAR*/
#PersonalToolbar {
  order: 2 !important;
}

/* Extra titlebar menu (above or below tabs, opens with alt) */
#titlebar #toolbar-menubar {
  order: 1 !important;
}
```

**Comment by datguypiko** [comment]
Look into this post
https://github.com/datguypiko/Firefox-Mod-Blur/issues/97#issuecomment-1838499179

![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/f36f5130-b5fc-44ab-85ef-7ebb19c3e6a9)

**Comment by anthonysgro** [comment]
brilliant, that fixed it! thanks
