### ISSUE TITLE
tabs overflow glitch

### ISSUE THREAD

**Issue by Exspecto322** [datguypiko/Firefox-Mod-Blur#122]
When tabs overflow the following glitch happens:

![firefox_7pKvef1bEE](https://github.com/datguypiko/Firefox-Mod-Blur/assets/84108942/830b2260-49da-4d94-bc87-146cab289876)

Installed Mods:
* Auto hide Mods
  > Popout bookmarks bar
* Bookmarks Bar Mods
  > Bookmarks bar same color as toolbar
  > Transparent bookmarks bar
  > Centered bookmarks bar items
  > Remove folder icons from bookmarks
* Compact extensions menu
  > Style 1
* Homepage mods
  > Circular homepage shortcuts
  > Remove text from homepage shortcuts
* Icon and Button Mods
  > Firefox view icon change
  > Icons in main menu
  > Menu icon change
  > White github icon
  > uBlock icon change
* Min-max-close control buttons
  > Right side MacOS style buttons\MenuButtonsOnLeft
* Privacy mods
  > Blur Username in Sync menu
  > Blur Username in main menu
  > Change main menu username
* Search Bar Mods
  > Search box - dots show only on hover
  > Search box - no border
  > Search box - transparent background
* Tabs Bar Mods
  > Colored sound playing tab
  > Pinned Tabs - no background color
  > Tabs - transparent background color

Installed Theme: None

I use a theme called Dark-Space-Theme alongside with this one but that doesn't seem to be the issue as when no theme is active still happens.

**Comment by datguypiko** [comment]
I tried with all the same mods but I couldn't reproduce the issue.

What versions did you download of my files?

What Operating System are you using?

What version of firefox do you have?

**Comment by Exspecto322** [comment]
Tried what you said Firefox without any files from the files works fine. tried removing one by one, only removing userChrome.css fixed the issue,  and when modifying userChrome.css  only deleting the #tabbrowser-tabs "{ }" part allowed me to open 4 more tabs than usual but glitch still happens.
pinned tabs seem to be affected too when resizing Firefox they overlap the Firefox View button


https://github.com/datguypiko/Firefox-Mod-Blur/assets/84108942/c3d8fc89-b092-49f5-a432-011d6753235e


I was on version 2.7.6, just updated to 2.7.7 and issue persist.
I am on Windows 10 Version 22H2 (OS Build 19045.4291)
Firefox Version 126.0 (64-bit)

**Comment by datguypiko** [comment]
Oh yeah I found what was the problem. It's the "Firefox view" button that I haven't used.
For now you can go to Customize toolbar mode and move the "Firefox View" button to other toolbars like bookmarks bar or top bar.

**Comment by datguypiko** [comment]
I released a fix https://github.com/datguypiko/Firefox-Mod-Blur/releases/tag/v2.7.8

**Comment by Exspecto322** [comment]
That fixed the issue! thank you!
