### ISSUE TITLE
Some icons from toolbar are invisible

### ISSUE THREAD

**Issue by Bearbro421** [datguypiko/Firefox-Mod-Blur#123]
Icons such as: go back & go forward (one page) and menu, are invisible until you hover over them, however even then icons do not appear but only their background.

EDIT: I forgot to mention that deleting menu_icon_change_to_firefox.css does not change anything

https://github.com/datguypiko/Firefox-Mod-Blur/assets/170178731/3347d618-184d-4aba-be6a-f0fd34e70c4d

![mods](https://github.com/datguypiko/Firefox-Mod-Blur/assets/170178731/ac670ef6-8b22-40de-82c6-1ba8237bc378)

**Comment by datguypiko** [comment]
Feels like you are missing the image folder.
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/57e1cffa-1fc2-4e23-b3d2-d74947de4764)

This is how file structure should look like 

![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/0af3c125-493e-4719-9af7-a3705d2d85af)
