### ISSUE TITLE
Differences betwwen versions

### ISSUE THREAD

**Issue by 1111Al** [datguypiko/Firefox-Mod-Blur#124]
Two screenshots, 1) is Mod Blur 2.3 applied to FF 110 (with Mica transparence), the second screenshots is the ModBlur 2.7.8 applied to FF 126.0.1 with mica too. Why 110 is perfect whereas 126 is so broken?

![Senza titolo1](https://github.com/datguypiko/Firefox-Mod-Blur/assets/122782530/5f8360a9-6573-400b-a741-042d3a747920)

![Senza titolo2](https://github.com/datguypiko/Firefox-Mod-Blur/assets/122782530/b2dac60f-c3af-4a56-91a4-49476e7cdddf)

**Comment by datguypiko** [comment]
Because firefox devs changed something with 117.x version and micaforeveryone has been broken since.

**Comment by 1111Al** [comment]
> Because firefox devs changed something with 117.x version and micaforeveryone has been broken since.
It's broken even without mica and other mods files, just you add the usercrome.css file to the normal version of FF and it breaks.

**Comment by datguypiko** [comment]
show me what's broken without mica.

**Comment by 1111Al** [comment]
Ok thanks for tip, I rechecked there was a wrong file structure. Now there is just one difference with ver 110, the close (x) of the tabs is on the right, in the 110 instead it is consistently to the left of the tab. Last thing; editing the ccs file is it possible to leave the three buttons (max/min/close) colored even without hover on them?

**Comment by datguypiko** [comment]
I tried the DWMBlur but it doesnt really blur anything, as broken as micaforeveryone (w11)
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/adfae201-a27e-4870-a46a-4d7d48af23d2).

I dont remember close button ever being on the left side. For older versions I would use older files anyway that you can find in releases if you still on 110.

For the min-max-close buttons open this "min-max-close_buttons.css" file and remove this line
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/0ea54f60-dc6f-4c2a-a7af-5432c047e1f3)

**Comment by 1111Al** [comment]
I solved with the code below added to tab section. Mica on my 126 looks to be working well

![Senza titolo](https://github.com/datguypiko/Firefox-Mod-Blur/assets/122782530/2a2b927d-1fb6-4dc0-8753-d9aa71fd3504)


`.tabbrowser-tab .tab-close-button {
   opacity: 0;
   margin-left: -4.5px !important;
   margin-right: 2px !important;
 }
 .tabbrowser-tab:not(:hover) .tab-close-button {
   display:none;
 }
 .tabbrowser-tab:not([pinned="true"]):hover .tab-close-button {
   opacity: 1;
   margin-inline-end: 0;
   order:-1 !important;
   display:unset !important;
 }
  .tabbrowser-tab:not([pinned="true"]):hover .tab-icon-stack {
   -moz-box-ordinal-group: 99999 !important;
 }
 .tabbrowser-tab:not([pinned="true"]):hover .tab-icon-stack:not([indicator-replaces-favicon]) {
   display: none;
 }`
