### ISSUE TITLE
Always show site info and bookmark in URL bar?

### ISSUE THREAD

**Issue by yourfriendaaron** [datguypiko/Firefox-Mod-Blur#125]
Hi,

Love the theme. It's beautiful and I use it as my daily driver, but is it possible to add a mod to always show the site info (lock icon) and bookmark star in the URL bar? I thoroughly checked the mod folders and couldn't find one, unless I'm a big dummy, which is definitely possible.

Thanks

**Comment by datguypiko** [comment]
You can remove all code in userChrome.css from line 1106 to 1321.

**Comment by yourfriendaaron** [comment]
That worked great, thanks!
