### ISSUE TITLE
Firefox 127 - icons in main menu broke

### ISSUE THREAD

**Issue by xfzv** [datguypiko/Firefox-Mod-Blur#126]
After updating to Firefox 127:
![Untitled](https://github.com/datguypiko/Firefox-Mod-Blur/assets/78810647/43c0b168-05a0-4e5b-b95a-0ee50632075b)

Wrong color for most icons (black foreground) and no padding between the icons and the first letter of entries.

**Comment by datguypiko** [comment]
I updated it.
https://github.com/datguypiko/Firefox-Mod-Blur/tree/master/EXTRA%20MODS/Icon%20and%20Button%20Mods/Icons%20in%20main%20menu


Latest updated source of this modification can be found [here](https://mrotherguy.github.io/firefox-csshacks/?file=iconized_main_menu.css) if you ever need it.
