### ISSUE TITLE
[Feature Request] Split out MMC wrapping to its own file

### ISSUE THREAD

**Issue by helpimnotdrowning** [datguypiko/Firefox-Mod-Blur#128]
Would you be able to split out the MMC wrapping (sections beginning at https://github.com/datguypiko/Firefox-Mod-Blur/blob/1122840677530a3af46a25bb42bf6b8fa2a4ed69/userChrome.css#L814 and https://github.com/datguypiko/Firefox-Mod-Blur/blob/1122840677530a3af46a25bb42bf6b8fa2a4ed69/userChrome.css#L1438 ) to their own files? I use the rest of the theme without issue, but I frequently shrink the window below 670px, which causes me to have to resize it again, since my other modifications can break things:
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/35247379/4bc075bf-7f2e-4bf5-8b80-fe05b4a5125a)
(minimize button is hidden under tab sidebar)

I wouldn't mind doing it myself & editing the README as well if you'd like.

**Comment by datguypiko** [comment]
I will think about it in the next version as I rewrite a lot of stuff right now.
