### ISSUE TITLE
Search bar is not centralized in homepage

### ISSUE THREAD

**Issue by Notori0** [datguypiko/Firefox-Mod-Blur#131]
Currently i'm using this theme in Librewolf, which may be the reason why i'm not seeing the firefox logo at the side of the search bar. This makes my homepage look very wrong

Preview of the issue:
![Captura de tela de 2024-07-09 17-09-22](https://github.com/datguypiko/Firefox-Mod-Blur/assets/175158563/d47743e5-4ae0-45cc-ae85-8f56ca3b1329)

Would it be possible for me to remove the firefox logo and centralize the searchbar by tweaking the Usercss? Btw, thank you very much for this awesome theme, so far it's the best for my usecase!

**Comment by anthonysgro** [comment]
this just happened to me as well, idk if it was a firefox update or something but today my address bar became centered instead of on the left

**Comment by datguypiko** [comment]
> this just happened to me as well, idk if it was a firefox update or something but today my address bar became centered instead of on the left.
> 
> I am using the searchbox_text_align_left mod here: https://github.com/datguypiko/Firefox-Mod-Blur/tree/master/EXTRA%20MODS/Search%20Bar%20Mods/Search%20box%20-%20text%20aligned%20left%20side
> 
> so it seems that needs an update now

download the latest "searchbox_text_align_left" file it was updated after v2.8 was posted.

**Comment by datguypiko** [comment]
> Would it be possible for me to remove the firefox logo and centralize the searchbar by tweaking the Usercss? Btw, thank you very much for this awesome theme, so far it's the best for my usecase!

Yeah, add this code to userContent.css

center horizontally 
```css
.logo-and-wordmark { display:none !important;}
```

if you want to center vertically 
```css
.outer-wrapper {
  display: flex !important;
  padding-top: unset !important;
}
```

**Comment by Notori0** [comment]
> > Would it be possible for me to remove the firefox logo and centralize the searchbar by tweaking the Usercss? Btw, thank you very much for this awesome theme, so far it's the best for my usecase!
> 
> Yeah, add this code to userContent.css
> 
> center horizontally
> 
> ```css
> .logo-and-wordmark { display:none !important;}
> ```
> 
> if you want to center vertically
> 
> ```css
> .outer-wrapper {
>   display: flex !important;
>   padding-top: unset !important;
> }
> ```

Added these to my userchrome.css file and unfortunately the issue still persists, maybe a firefox update broke it?

**Comment by datguypiko** [comment]
Add it to userContent not userChrome file.

**Comment by datguypiko** [comment]
add it in userContent file not userChrome.

at around line 500 would be preferred
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/b1d1e8a6-edc3-4870-8b3a-7c7dc67db313)

**Comment by Notori0** [comment]
> add it in userContent file not userChrome.
> 
> at around line 500 would be preferred ![image](https://private-user-images.githubusercontent.com/61329159/347840412-b1d1e8a6-edc3-4870-8b3a-7c7dc67db313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MzE5NjksIm5iZiI6MTcyMDczMTY2OSwicGF0aCI6Ii82MTMyOTE1OS8zNDc4NDA0MTItYjFkMWU4YTYtZWRjMy00ODcwLThiM2EtN2M3ZGM2N2RiMzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDIxMDEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZGM5ZjQ4YjJkMDIwNTkzNzI0MTk5MmEwNGI3OGNhMTkzMDQyNjhiN2IzODY4OTk5ZWJiN2UwMDM4OGZmOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RwBmPHjco4TNtAtiM3GRXXz8tWFJcgySZy4VS1wsJvw)
> 
> ![image](https://private-user-images.githubusercontent.com/61329159/347840671-c64f0352-b3b6-4c53-96d5-920161fe82f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MzE5NjksIm5iZiI6MTcyMDczMTY2OSwicGF0aCI6Ii82MTMyOTE1OS8zNDc4NDA2NzEtYzY0ZjAzNTItYjNiNi00YzUzLTk2ZDUtOTIwMTYxZmU4MmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDIxMDEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNTRiNTVlZTY3NmY2MmRhOTE0MDk2ZDZjZTY5ODU2NmRhOTMxYTcyZTNiNTRhOGUyMjg1NWQ2NDc3ODljZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SCxz2sJ2YWrRP3TH8AxR9D9hxoKzre1KBL0nbjWm9qY)

Oh i've misread that completely, my bad! Put the code in the correct file now and that seems to do the trick, my homepage is fine now :)
Will close the issue.
