### ISSUE TITLE
Can I get an updated guide for tabs on top please?

### ISSUE THREAD

**Issue by superdragon1772** [datguypiko/Firefox-Mod-Blur#132]
I'm struggling putting this together with the new updates. Can I get an updated guide for tabs on top please?

https://github.com/datguypiko/Firefox-Mod-Blur/issues/97

**Comment by datguypiko** [comment]
I added it to userChrome. Redownload the file https://github.com/datguypiko/Firefox-Mod-Blur/blob/master/userChrome.css

To enable it type `about:config` in searchbar and add `firefoxcss.tabs.on.top.enable`
