### ISSUE TITLE
2.8 Search Bar Mods Broken

### ISSUE THREAD

**Issue by Exspecto322** [datguypiko/Firefox-Mod-Blur#133]
Searchbar looks like this in 2.7.8
![firefox_pw2wMwPp8M](https://github.com/user-attachments/assets/25ed4ad4-a459-4ba2-8a9f-bca03cc486c7)
after update looks like this:
![image](https://github.com/user-attachments/assets/c0f0c57d-805a-4f6b-8f46-2af73744e4cc)
it seems like it broke no border and transparent background mods for me if I go back to previous version it looks as intended, I have the following set up:
Installed Mods:
* Auto hide Mods
  > Popout bookmarks bar
* Bookmarks Bar Mods
  > Bookmarks bar same color as toolbar
  > Transparent bookmarks bar
  > Centered bookmarks bar items
  > Remove folder icons from bookmarks
* Compact extensions menu
  > Style 1
* Homepage mods
  > Circular homepage shortcuts
  > Remove text from homepage shortcuts
* Icon and Button Mods
  > Firefox view icon change
  > Icons in main menu
  > Menu icon change
  > White github icon
  > uBlock icon change
* Min-max-close control buttons
  > Right side MacOS style buttons\MenuButtonsOnLeft
* Privacy mods
  > Blur Username in Sync menu
  > Blur Username in main menu
  > Change main menu username
* Search Bar Mods
  > Search box - dots show only on hover
  > Search box - no border
  > Search box - transparent background
* Tabs Bar Mods
  > Colored sound playing tab
  > Pinned Tabs - no background color
  > Tabs - transparent background color

Installed Theme: None

Windows 10 Pro 10.0.19045 Build 19045

**Comment by datguypiko** [comment]
I fixed it. Will add to the zip file later you can download file from here 
https://github.com/datguypiko/Firefox-Mod-Blur/tree/master/EXTRA%20MODS/Search%20Bar%20Mods/Search%20box%20-%20transparent%20background

https://github.com/datguypiko/Firefox-Mod-Blur/tree/master/EXTRA%20MODS/Search%20Bar%20Mods/Search%20box%20-%20no%20border

**Comment by Exspecto322** [comment]
That fixed it, thanks!
