### ISSUE TITLE
The icons on the toolbar on the right are shifted

### ISSUE THREAD

**Issue by DIMFLIX-OFFICIAL** [datguypiko/Firefox-Mod-Blur#135]
![image](https://github.com/user-attachments/assets/0ea47cd8-071f-4fc6-8d8e-fbbf171aafb6)
![image](https://github.com/user-attachments/assets/954ab08c-a5d8-4d26-9498-976dee6c07cc)

**Comment by datguypiko** [comment]
Change `--firefoxcss-control-buttons-margin: 95px;` value to `0px` in `userChrome.css` file.
In the next bigger 3.0 update if works correctly it will automatically set margin depending on Operating system, number of buttons and position.

**Comment by datguypiko** [comment]
Are you using Librewolf firefox? Because I can see some buttons not rotated in search bar.
