### ISSUE TITLE
min-max-close buttons still appears when opening bookmarks in full window view

### ISSUE THREAD

**Issue by githlacker** [datguypiko/Firefox-Mod-Blur#136]
the min-max-close buttons is displaying even when opening bookmarks (in full screen mode) when adding the min-max-close_buttons.css
![Screenshot from 2024-07-24 18-56-44](https://github.com/user-attachments/assets/dbd48a2b-2c51-406d-831f-17bff8d4c0c5)

**Comment by datguypiko** [comment]
Fixed. Redownload the userChrome.css file https://github.com/datguypiko/Firefox-Mod-Blur/blob/master/userChrome.css

**Comment by githlacker** [comment]
that was fast. thank you

**Comment by datguypiko** [comment]
So using this fix creates this weird bug for me, idk if you getting this
![Screenshot 2024-07-26 121102](https://github.com/user-attachments/assets/a0e84aa3-a7e8-4274-bc3e-681e5e74d5b1)

I reversed the changes for now but I will probably fix it different way but it will cause the buttons to move to their default bar in fullscreen.

**Comment by githlacker** [comment]
> So using this fix creates this weird bug for me in fullscreen mode, idk if you getting this
> ![Screenshot 2024-07-26 121102](https://github.com/user-attachments/assets/a0e84aa3-a7e8-4274-bc3e-681e5e74d5b1)
> 
> I reversed the changes for now but I will probably fix it different way but it will cause the buttons to move to their default bar in fullscreen.

Idk know it's fine for me

**Comment by datguypiko** [comment]
> > So using this fix creates this weird bug for me in fullscreen mode, idk if you getting this
> > ![Screenshot 2024-07-26 121102](https://private-user-images.githubusercontent.com/61329159/352484532-a0e84aa3-a7e8-4274-bc3e-681e5e74d5b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODgwMTMsIm5iZiI6MTcyMTk4NzcxMywicGF0aCI6Ii82MTMyOTE1OS8zNTI0ODQ1MzItYTBlODRhYTMtYTdlOC00Mjc0LWJjM2UtNjgxZTVlNzRkNWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA5NTUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYzEzY2Q4NTQ0ZTNlMGRhNzRjZDc3OTY4Y2FlYWYyODRjOWM3YWQyZDAwNjQyMDc1Y2FmOTA4Mjc4MGViZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CP2BdkosreE6bW6fJ_Rm2Yb7bfaH9nBqhZ2YvEybun4)
> > I reversed the changes for now but I will probably fix it different way but it will cause the buttons to move to their default bar in fullscreen.
> 
> I don't know, it's fine for me...

I wasnt very specific. But when you use bookmarks bar and you go in fullscreen (F11) mode does this icon appear to you in bookmarks bar? (Of course if it already overflows because of too many bookmarks you wont see it)

![image](https://github.com/user-attachments/assets/554a0967-ee61-4a82-8703-020d8b03be9f)

You on windows 11 right?

**Comment by githlacker** [comment]
> > > So using this fix creates this weird bug for me in fullscreen mode, idk if you getting this
> > > ![Screenshot 2024-07-26 121102](https://private-user-images.githubusercontent.com/61329159/352484532-a0e84aa3-a7e8-4274-bc3e-681e5e74d5b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODgwMTMsIm5iZiI6MTcyMTk4NzcxMywicGF0aCI6Ii82MTMyOTE1OS8zNTI0ODQ1MzItYTBlODRhYTMtYTdlOC00Mjc0LWJjM2UtNjgxZTVlNzRkNWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA5NTUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYzEzY2Q4NTQ0ZTNlMGRhNzRjZDc3OTY4Y2FlYWYyODRjOWM3YWQyZDAwNjQyMDc1Y2FmOTA4Mjc4MGViZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CP2BdkosreE6bW6fJ_Rm2Yb7bfaH9nBqhZ2YvEybun4)
> > > I reversed the changes for now but I will probably fix it different way but it will cause the buttons to move to their default bar in fullscreen.
> > 
> > 
> > I don't know, it's fine for me...
> 
> I wasnt very specific. But when you use bookmarks bar and you go in fullscreen (F11) mode does this icon appear to you in bookmarks bar? (Of course if it already overflows because of too many bookmarks you wont see it)
> 
> ![image](https://private-user-images.githubusercontent.com/61329159/352490097-554a0967-ee61-4a82-8703-020d8b03be9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODg4NjQsIm5iZiI6MTcyMTk4ODU2NCwicGF0aCI6Ii82MTMyOTE1OS8zNTI0OTAwOTctNTU0YTA5NjctZWU2MS00YTgyLTg3MDMtMDIwZDhiMDNiZTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDEwMDkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhYWQyZTM2MjhkNzU1MDQ4NDYzYmI1Njc2YzdkODUxNGIyMTMyYmYyOTk3NjgxMTQ3YTgwMDI3ZTZjOTIxMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LBWhbUfnivM58SJkbLsIzHTQVhHGKKdW0T817BKDkAQ)
> 
> You on windows 11 right?

No, it's still fine for me, and also I'm on Linux.
