### ISSUE TITLE
窗口最大化时鼠标移动到屏幕最上方边缘无法触发最小化最大化关闭这三个按钮

### ISSUE THREAD

**Issue by pessnoom** [datguypiko/Firefox-Mod-Blur#137]
如图所示，其他的按钮做了边缘触发优化，而 最小化、最大化、关闭这三个按钮无法正常在边缘触发，作为一个用了很多年  windows 的人，不能用鼠标盲操作往右上角直接一滑关闭，很影响使用，请麻烦修复一下，感谢。

正常情况：
![Snipaste_2024-08-05_05-49-53](https://github.com/user-attachments/assets/e3d01694-d97c-42c9-ae6f-b33977974d03)
![Snipaste_2024-08-05_05-50-04](https://github.com/user-attachments/assets/b304d912-d965-4c98-87a3-6c9852fa7354)
非正常情况：
![Snipaste_2024-08-05_05-50-18](https://github.com/user-attachments/assets/f8a7851f-d806-4794-9b97-22846d6d4f26)
![Snipaste_2024-08-05_05-50-36](https://github.com/user-attachments/assets/d4270db3-6f91-40db-b71b-0e81476a5d21)
![Snipaste_2024-08-05_06-01-29](https://github.com/user-attachments/assets/0f68cfb6-3287-4026-acd4-7903a8a7b18e)
![Snipaste_2024-08-05_06-03-21](https://github.com/user-attachments/assets/ce35fa21-34a3-437c-8378-c0d1bdc5fd30)

**Comment by pessnoom** [comment]
![Uploading Snipaste_2024-08-05_06-01-29.png…]()

**Comment by pessnoom** [comment]
![Snipaste_2024-08-05_06-01-29](https://github.com/user-attachments/assets/7b4abbd3-4687-434f-a182-2307a15b8b90)

**Comment by datguypiko** [comment]
I will check if that can be done on the 3.0 version.

**Comment by pessnoom** [comment]
> 我将检查是否可以在 3.0 版本上完成。

thanks

**Comment by datguypiko** [comment]
> Thanks for the incredible work! I understand that the issue will be addressed in a future release. In the meantime, is there a CSS snippet or workaround available that could help achieve this?

yeah you can edit userChrome file these:

1. Comment out or delete these lines 

![Image](https://github.com/user-attachments/assets/7e6d8405-e4ab-4b24-a5e1-ccccd3512b89)

2. Below change `top:1px;` to `top:0px;`

3. Add this code anywhere at the bottom for the corner of close button not to be rounded.
```css
  .titlebar-buttonbox-container .titlebar-button.titlebar-close {
      border-top-right-radius: 0px !important;
  }
```
