### ISSUE TITLE
默认图标适配不全，请求图标风格统一

### ISSUE THREAD

**Issue by pessnoom** [datguypiko/Firefox-Mod-Blur#138]
我非常喜欢这个主题所做的一切，风格样式交互设计等等，但是目前还有一些常用的默认图标没有做适配，用红圈标注的是默认的直角风格，没有做圆角圆润风格的优化，放在一起割裂感很明显，您做的粗线条图标非常好看，希望有空的时候能帮忙适配一下其他默认图标，统一设计风格，非常感谢！

如图所示：
![Snipaste_2024-08-05_05-56-58](https://github.com/user-attachments/assets/67523859-d4f3-4c6c-a869-5d4f5a2e449c)
![Snipaste_2024-08-05_05-57-14](https://github.com/user-attachments/assets/8472f6c5-330f-42f7-a616-135d1dc8327d)
![Snipaste_2024-08-05_06-15-46](https://github.com/user-attachments/assets/25f671b0-43d5-4dd0-9b06-437f89d5d276)

**Comment by datguypiko** [comment]
No plans for now, most of them looks fine. The only Icon I would change is probably the refresh button but it breaks the animation.

**Comment by pessnoom** [comment]
> 目前还没有计划，大部分看起来都不错。我唯一要更改的图标可能是刷新按钮，但它会破坏动画。

是的，如果不追求极致，不仔细看的话影响不大，可以容忍的问题，在深色模式下表现不明显，浅色模式下比较容易发现，主要是线条粗细和颜色镂空等等的问题，可惜我不会css和html，没办法自己改的很好，所以还是需要专业人士帮忙
![Snipaste_2024-08-05_23-55-43](https://github.com/user-attachments/assets/c34cc746-3fb3-4f5a-9fff-611e3f1876c4)
![Snipaste_2024-08-05_23-55-48](https://github.com/user-attachments/assets/dd7d97d1-f4f6-446f-be13-8f4a81317153)
