### ISSUE TITLE
Pinned tab underline.

### ISSUE THREAD

**Issue by Ryan-da-ghost** [datguypiko/Firefox-Mod-Blur#14]
Could you add a system where the pinned tabs have an underline?  If not could you tell us how to do this ourselves?

**Comment by datguypiko** [comment]
So for example if you are using "**_userChrome-imUsingThis.css_**", you can add this code to the userChrome file (change "#a3ffdc" to any color code you want; "2px" the size of it; "10px" change the roundness)
How it looks

 ![p](https://i.imgur.com/v0w45PB.png)
```
#tabbrowser-tabs .tab-stack .tab-content[pinned] {
    border-bottom: 2px solid #a3ffdc !important;
    border-radius: 10px !important;
}
```

----------------

If you are using default theme "**_userChrome.css_**" add this code. 

 ![p2](https://i.imgur.com/SlDkJ5y.png)

```
#tabbrowser-tabs .tabbrowser-tab[pinned] .tab-stack::after {
    content: "";
    position: absolute;
    border-bottom: 2px solid #ec64ffa3;
    width: 60%;
    left: 0;
    right: 4px;
    margin-left: auto;
    bottom: 2px;
    margin-right: auto;
    border-radius: 50px;
    bottom: 32px;
    height: 1px;
}
```

**Comment by datguypiko** [comment]
I will leave it open for now if you have any question.
