### ISSUE TITLE
Unable to click tabs at top edge of screen

### ISSUE THREAD

**Issue by Rokym** [datguypiko/Firefox-Mod-Blur#140]
I'm encountering an issue with my Firefox CSS modifications. When I move the mouse pointer all the way to the top of the screen and try to click on a tab, it seems like I'm clicking the border of the browser window instead of the tab itself. This prevents the tab from being selected. Could anyone advise on which CSS setting I need to adjust to ensure that the tabs remain clickable when the mouse is at the top edge of the screen?
 
Thank you!

![L5KvcXLjjn](https://github.com/user-attachments/assets/50d9f38b-b66a-4167-8140-462fdc98825b)

**Comment by datguypiko** [comment]
you have your tabs set at the top?

**Comment by Rokym** [comment]
> you have your tabs set at the top?

yeah i moved them to the top.  seems the tabs don't go all the way to the top of the browser so when i click at the very top of my screen, its actually click the browser itself and not the tab

**Comment by datguypiko** [comment]
Set padding-top to 0px should work if you have set "firefoxcss.tabs.on.top.enable" in about:config.
![image](https://github.com/user-attachments/assets/b88c6824-27d7-4ca4-b9b3-92bb6404852f)

**Comment by Rokym** [comment]
> Set padding-top to 0px in userChrome.css file, should work if you have set "firefoxcss.tabs.on.top.enable" in about:config. ![image](https://private-user-images.githubusercontent.com/61329159/356819744-b88c6824-27d7-4ca4-b9b3-92bb6404852f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMTMxNDksIm5iZiI6MTcyMzMxMjg0OSwicGF0aCI6Ii82MTMyOTE1OS8zNTY4MTk3NDQtYjg4YzY4MjQtMjdkNy00Y2E0LWI5YjMtOTJiYjY0MDQ4NTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDE4MDA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZjc5ODI0M2M3ZDRmNDc1ZjNiNjc1Y2I5ZmJmYzIyODRiY2RmMGVmOGVlZDM2ZWI0ZDQwODVlZDAxODYyMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Fh6jszuawlBnJbh0hEUJfPtxuZsxjE2NsTo1xBdHLc)
i fucking love you, thank you so much!
