### ISSUE TITLE
Window control buttons disappearing

### ISSUE THREAD

**Issue by rh1nehart** [datguypiko/Firefox-Mod-Blur#141]
When I press alt window control buttons disappear

https://github.com/user-attachments/assets/019348f8-8c9f-4319-916f-f0d9d50462a3

**Comment by rh1nehart** [comment]
Forgot to say. I'm using FF 129 Stable

**Comment by datguypiko** [comment]
Should be fixed now redownload the userChrome file https://github.com/datguypiko/Firefox-Mod-Blur/blob/master/userChrome.css
