### ISSUE TITLE
Blur issue

### ISSUE THREAD

**Issue by Golem730** [datguypiko/Firefox-Mod-Blur#142]
Hi,
My blur doesn't work.
I dont know if I do a misstake but on the V129 of firefow my blur doesnt work.
Thanks for you work this tools is so cool to have a cool browser.

**Comment by datguypiko** [comment]
micaforeveryone blur hasnt been working for some time.

**Comment by Golem730** [comment]
Is working with another style ?

**Comment by datguypiko** [comment]
a what?

**Comment by Golem730** [comment]
can we get the blur on another style ?

**Comment by datguypiko** [comment]
on what style?
