### ISSUE TITLE
Bookmark Tab

### ISSUE THREAD

**Issue by tomaseye** [datguypiko/Firefox-Mod-Blur#145]
Hi,
I have 2 issues 
1. when I try to Bookmark a Tab this happens  

https://github.com/user-attachments/assets/c5185f4a-f55d-48f0-a0d4-4a33338bcfc0

2. while being on Bitwarden website i try to add a new item and something like this 

https://github.com/user-attachments/assets/62541c1c-cb33-49bb-8b16-00f8166f0791

I don't know if these have any relation, but both issues only occur when using the theme.

Thanks

**Comment by datguypiko** [comment]
I fixed the second one but I dont know which menu is that for the first one with bookmarks.

Bookmarking menu for me looks like this 
![{43D7371B-8AF0-429D-9C7B-575927DF91EE}](https://github.com/user-attachments/assets/3f50bfce-5c56-420d-be60-9f0c48a2b702)

**Comment by datguypiko** [comment]
I fixed it. Redownload userChrome file
https://github.com/datguypiko/Firefox-Mod-Blur/blob/master/userChrome.css

**Comment by tomaseye** [comment]
This created another problem.

https://github.com/user-attachments/assets/afb0d17f-3bce-404b-b9ff-37ea6760c912

**Comment by datguypiko** [comment]
oh right, was missing some code that I didnt add
try now 
https://github.com/datguypiko/Firefox-Mod-Blur/blob/master/userChrome.css

**Comment by datguypiko** [comment]
Btw I'm fixing the home screen menu too, will add changes in few days.
![{5603005D-9F53-49D2-80B6-0C3ED199DC03}](https://github.com/user-attachments/assets/6d51ee97-2010-44a0-b312-b8a1a37d6091)

![{E0AD0B12-4D7B-4B31-9F04-403FFCE725E9}](https://github.com/user-attachments/assets/2dc80c4d-aa32-4452-b3d9-1cb56c6234c0)

**Comment by tomaseye** [comment]
Everything fixed now, thanks!
