### ISSUE TITLE
Firefox 130 - Invisible navigation buttons

### ISSUE THREAD

**Issue by Titaniumtown** [datguypiko/Firefox-Mod-Blur#147]
Latest Firefox 130 update results in the back and forward buttons to be invisible.

Example:
![image](https://github.com/user-attachments/assets/393c27df-a457-48b5-99f9-4883979d4640)

**Comment by datguypiko** [comment]
You probably missed a folder
![{6D9FE752-DE30-4BE6-8052-3BC3D94E72F7}](https://github.com/user-attachments/assets/10083bbc-d1ba-4d2e-923d-f04ef66c9d6f)
