### ISSUE TITLE
The scroll bar is always visible and different from the usual one

### ISSUE THREAD

**Issue by duckaleuze** [datguypiko/Firefox-Mod-Blur#149]
-discord scrollbar with the theme:

![sdfgh43g](https://github.com/user-attachments/assets/b13ff1ba-bb94-46a1-9e83-f66f84942264)

-discord with no theme:

![image_png](https://github.com/user-attachments/assets/6ea19340-044c-4c30-816a-f48cf04531a4)

only appears on hover: 

![sdfgasdfgasd](https://github.com/user-attachments/assets/234a045e-b8ae-4873-849c-6c70ac039176)

-whatsapp with the theme: 

![sdfgasdfgasdf](https://github.com/user-attachments/assets/02f388de-15b0-4b78-b5f2-9b7d21778dc0)

-whatsapp with no theme: 

![sdfgsdfhad](https://github.com/user-attachments/assets/d3f6c4f3-baf7-45e7-bdbe-699f7a736033)

can you fix this? I would like the scrollbar to act like vanilla firefox, maybe you could add a mod to toggle

**Comment by datguypiko** [comment]
My theme doesnt change scrollbar it looks the same with or without it.
What OS are you using?
On hover 
![{D6298474-5C51-4BE9-8B23-2C2A9D1560B7}](https://github.com/user-attachments/assets/f77845e0-f904-41d7-8732-77e234b04260)
non hover 
![{7C082C4C-A7AC-4C13-BD93-DE3C50ED0119}](https://github.com/user-attachments/assets/42f7d016-f9ba-45eb-b8fe-f7221d1e49f5)

**Comment by duckaleuze** [comment]
that's weird, I'm on windows 10, this is what's inside my chrome folder:

![image](https://github.com/user-attachments/assets/3c2c8e04-485d-465f-baa2-689791f19ae1)

**Comment by datguypiko** [comment]
So I was looking at main scroll bar which was fine but I found that the inside page/secondary scroll wheels were different. I deleted some leftover code let me know if it changes anything.
redownload userContent.css file https://github.com/datguypiko/Firefox-Mod-Blur/blob/master/userContent.css

**Comment by duckaleuze** [comment]
yeah it worked, now all the scroll bars look like normal firefox, thanks :D
