### ISSUE TITLE
Weird Amount of Space When Displaying URLS in Adress Bar.

### ISSUE THREAD

**Issue by Solarwindbear** [datguypiko/Firefox-Mod-Blur#15]
As the title says whenever searching, the address bar leaves a weird amount of space between the site title and url. 

![space issue](https://user-images.githubusercontent.com/83036803/115776006-3aee5400-a379-11eb-86bb-5209339af70c.png)

**Comment by datguypiko** [comment]
Thanks. Fixed 👍

**Comment by PixsaOJ** [comment]
@datguypiko can you point to commit you fixed this? Because for me
```
#urlbar {
		text-align: center !important;
	}
```
This actually makes result links go to center

**Comment by PixsaOJ** [comment]
Somewhere near line 262 do this to fix it:
```
#urlbar {
		box-shadow: none !important;
	}
	#urlbar .urlbar-input-box {
	    text-align: center;
	}
```
I am using  `userChrome-imUsingThis.css`  From `For Older Firefox (Not Proton)` fodler
