### ISSUE TITLE
Box of blue color shows up in the top right of the firefox UI.

### ISSUE THREAD

**Issue by michelklaasen** [datguypiko/Firefox-Mod-Blur#151]
Hi there,

I just installed the theme on Windows 11 and MacOS 14.6.1. Both are running Firefox 130.0.1.

Then, a blue color shows in the top right of the Firefox UI, see the image 👇 

![Blue color in UI](https://github.com/user-attachments/assets/69ec780b-381c-46c1-af92-80905d1b027d)

I checked it out with the toolbox and the line of CSS that is responsible for this is one 👇 turning it off will remove the color.

![Responsible CSS](https://github.com/user-attachments/assets/5dff040f-f67e-40ca-ac8b-b9bd758a9260)

And I managed to get rid of the little box thing by adding this line of CSS in userChrome.css. Now, I haven't investigated the theme so I'm not sure what I'm doing but it works:

`#navigator-toolbox { 
  :root[lwtheme-image] & {
    background-image: var(--lwt-additional-images) !important;
  }
}`

So, yeah, I don't think that color is supposed to be there right?

Greetings

(and thanks for the awesome theme)

**Comment by datguypiko** [comment]
Probably because you are using custom theme 
![{5EE4A614-8356-4D30-A5B0-478F19EEED5A}](https://github.com/user-attachments/assets/e508f911-8994-4b07-8f2e-d56b1ba9ca5c)

Simple fix is just adding this, I will add it to userChrome.css

```css
#navigator-toolbox {
  background-image: none !important;
}
```

**Comment by michelklaasen** [comment]
Hey sorry I never got back to you.

You were totally right by the way. It's caused by the custom theme and that particular line of code fixes it.

Wasn't aware I had that theme running.

Thanks.
