### ISSUE TITLE
Website Content Becomes Unreadable with Dark Background and Black Text When Using Dark Theme 

### ISSUE THREAD

**Issue by markebo** [datguypiko/Firefox-Mod-Blur#154]
I’ve encountered an issue while using this CSS theme where certain websites, such as BBC and Pinterest, display a black background with black text, making the content unreadable. This issue appears specifically on these sites, while other websites are rendered correctly. I believe it may be related to how the theme interacts with certain elements on these pages.
Could you please look into this issue? 

![Screenshot 2024-09-26 042632](https://github.com/user-attachments/assets/9d71ef70-6588-47fa-b5a1-616e6da02b7a)

**Comment by datguypiko** [comment]
I dont see it. Give me some specific direct links to it.

**Comment by markebo** [comment]
> I dont see it. Give me some specific direct links to it.

I removed the entire 'chrome' folder, but the issue still persists. I suspect it's due to the Firefox dark mode theme, not your CSS theme. Everything else is fine. Thank you.
