### ISSUE TITLE
question

### ISSUE THREAD

**Issue by kiyxshi** [datguypiko/Firefox-Mod-Blur#156]
hello dear developers, just wanted to ask if i can to change color of entire browser using ur theme .
![изображение](https://github.com/user-attachments/assets/81a27ac8-734a-4ba2-b98d-fa802ee20676)
how you can see there's gray browser and i want to change it to purple , how i can do it? it is possible, ty for response

**Comment by datguypiko** [comment]
You can open userChrome.css and change all of the colors. You can use online color editors.  
![{FD55AF77-F810-47B8-8948-EE0F4AD8A0E7}](https://github.com/user-attachments/assets/d8a85567-4b03-43bf-beeb-ffab33cb2f8d)
