### ISSUE TITLE
Tab bar is broken and full-width

### ISSUE THREAD

**Issue by kraibse** [datguypiko/Firefox-Mod-Blur#159]
After I installed this theme both with the installer and separately with the installer provided, this layout show in my Firefox Nightly with the `toolkit.legacyUserProfileCustomizations.stylesheets` set to `true`.

What am I missing in the installation to get the layout and the buttons as shown in the preview images?

![image](https://github.com/user-attachments/assets/3a3fb8ca-3590-4144-888d-6be7b106a1bf)

My installed extra mods from this repository:
![image](https://github.com/user-attachments/assets/0ec9ef24-a1eb-42d8-b808-3dc0ebcf825a)

My installed extra theme:
- Spill

**Comment by datguypiko** [comment]
Did you download this file ?
![{8344574C-DEF8-4F4C-9BEE-8F4642989BBD}](https://github.com/user-attachments/assets/c02ee689-c759-453f-9202-545732b4e0ef)

replace your userChrome.css with that file if you didnt.

**Comment by kraibse** [comment]
Thanks for the pointer. Seeing as I cloned the repository, I did not think to look in the releases section - issue solved.
