### ISSUE TITLE
mod-blur simple not working on Firefox dev edition

### ISSUE THREAD

**Issue by githlacker** [datguypiko/Firefox-Mod-Blur#160]
So after following the usual steps and all Firefox didn't get any effect from the css (also I tried the nightly chromecss)

**Comment by datguypiko** [comment]
Posta picture of your chrome folder.

**Comment by githlacker** [comment]
![image](https://github.com/user-attachments/assets/4b2f8358-3ad5-46af-9122-9dca967ecf5b)

and if it does have an effect this happens:
![image](https://github.com/user-attachments/assets/d60db4f2-cbe1-48c3-aad6-2d175ba878a5)

**Comment by datguypiko** [comment]
userChromeForNightly133or134.css if you downloaded this one you had to rename it to userChrome.css

Anyway just use stable version. Nightly gets broken too often.

**Comment by githlacker** [comment]
Alright this worked. thx
