### ISSUE TITLE
[FIX] Color correction for the "show searchbar dots only on hover" module.

### ISSUE THREAD

**Issue by SaiyajinK** [datguypiko/Firefox-Mod-Blur#161]
hi,

i just upgraded to firefox 133 and updated the theme to version 2.12. Everything works fine but i noticed a small problem with the module show_searchbar_dots_only_on_hover.css

Indeed when hovering the dots are totally black and not visible :

![firefox_50ngPBpCyS](https://github.com/user-attachments/assets/da3a6961-64f3-4f48-a9ae-f07668312ba3)

This can be fixed simply by modifying "show_searchbar_dots_only_on_hover.css" with these lines :

```
/* Only show dots in search bar when hovered */
#urlbar #identity-box::after,
#urlbar #page-action-buttons::before {
	opacity: 0;
}

#urlbar:hover #identity-box::after,
#urlbar:hover #page-action-buttons::before {
	opacity: 0.8;
	transition: opacity 100ms ease;
	filter: invert(1);
}
```

résultat : 
![firefox_9F8yTnslqH](https://github.com/user-attachments/assets/949b1dc0-565a-41c5-93b1-d68d7b19b50b)

Well, this was just to report it so you can integrate the fix for future uploads. 👋🏻

**Comment by datguypiko** [comment]
Enable "svg.context-properties.content.enabled" in about:config I will add a notification at the top for those who doesnt have it.

**Comment by datguypiko** [comment]
Added notification to v2.13 https://github.com/datguypiko/Firefox-Mod-Blur/releases/tag/v2.13

You dont need to redownload this if you enabled `svg.context-properties.content.enabled` already.
