### ISSUE TITLE
UI Disappears and Reloads When Opening Extension

### ISSUE THREAD

**Issue by B1ack3ye** [datguypiko/Firefox-Mod-Blur#162]
When clicking on an extension icon to open it, the entire Firefox UI disappears and the browser reloads.

https://github.com/user-attachments/assets/739cd1ca-4a12-4718-b689-5e715c49a712

**Comment by datguypiko** [comment]
I will check it. For now disable the icon and open it from the extension menu
![image](https://github.com/user-attachments/assets/a564ff8d-d683-4423-97f9-2f1e579c7cc6)
