### ISSUE TITLE
[BUG] Missing titlebar buttons

### ISSUE THREAD

**Issue by Undisputed00x** [datguypiko/Firefox-Mod-Blur#163]
The new update breaks buttons in the titlebar. Buttons are placed behind the bar which can be seen in the moment after when firefox is just launched and loads the UI. Applying an extra mod for the buttons doesn't make any change.

<details>
<summary>

### Picture

</summary>
<p>

![NoButtons](https://github.com/user-attachments/assets/0f591f96-0b08-4981-8176-0321c702d4a5)

</p>
</details>

**Comment by datguypiko** [comment]
You are missing this folder 
![image](https://github.com/user-attachments/assets/d96b2a51-63a9-4c0e-aed7-59d1cd201c70)

**Comment by Undisputed00x** [comment]
I can't understand what im doing wrong. The Assets folder is present in chrome

![image](https://github.com/user-attachments/assets/d4c7edba-aad5-41ea-a57e-1458a340215d)

**Comment by datguypiko** [comment]
Show me the Chrome folder

**Comment by Undisputed00x** [comment]
> Show me the Chrome folder

<details>
<summary>

### Image

</summary>
<p>

![image](https://github.com/user-attachments/assets/238c754c-3699-48ad-8272-6aeb9c185670)

</p>
</details>

**Comment by Undisputed00x** [comment]
> I cant reproduce it. Wait is this Linux or modified Windows 11?

Windows 11 24H2

**Comment by datguypiko** [comment]
> > I cant reproduce it. Wait is this Linux or modified Windows 11?
> 
> Windows 11 24H2

Feels like you have 3rd party program that somehow affecting the window, or maybe about:config preference that affects it.

**Comment by hb7098** [comment]
Get the update that dropped an hour ago.

https://github.com/datguypiko/Firefox-Mod-Blur/releases/tag/v2.14

**Comment by Undisputed00x** [comment]
> Oh yeah make sure you have the latest version.
> 
> You said "latest update", dont know if you meant my files or firefox update.

Done that, shutdown all Windows mods and reboot but no effect. Also im facing other bugs also with the update but maybe is my system's fault somehow. Gonna reinstall firefox and inform about the issue

**Comment by hb7098** [comment]
@Undisputed00x To be extra specific, download the update of this mod and reinstall the mod (delete the old assets folder and .css files and copy paste the new ones) and restart firefox. Worked fine for me.

**Comment by Undisputed00x** [comment]
Reinstalled and now its fixed, probably had messed with the config settings and created me issues

**Comment by Undisputed00x** [comment]
Found the problem which produced this problem, i had enabled `widget.windows.mica` in config.
