### ISSUE TITLE
[BUG] Hide list-all-tabs button doesn't work

### ISSUE THREAD

**Issue by Undisputed00x** [datguypiko/Firefox-Mod-Blur#164]
Like the title says this extra mod doesn't work in the new update.

<details>
<summary>

### Picture

</summary>
<p>

![hide-all-list-not-working](https://github.com/user-attachments/assets/5e7e1f7b-d116-4d7b-86fe-45f098752da6)

</p>
</details>

**Comment by datguypiko** [comment]
I should probably make a separate mod for that because it basically hides the button until tabs overflow. When tabs overflow it shows it.

**Comment by datguypiko** [comment]
I forgot that you can remove the button yourself in customization mode. Just drag the button from the toolbar.

**Comment by datguypiko** [comment]
![image](https://github.com/user-attachments/assets/0f53feb4-61b7-4851-8c5e-827ea44ff4f7)
