### ISSUE TITLE
Any solution? Inverted task bar

### ISSUE THREAD

**Issue by Anuneza** [datguypiko/Firefox-Mod-Blur#166]
I don't know if there is a shotcut that has produced this error, the only change I have made was changing the colors manually in userChrome.css and for obvious reasons the wallpaper.  I love this style of firefox and I wouldn't want to have to change it. 

thx

![Screenshot from 2024-11-26 17-36-58](https://github.com/user-attachments/assets/4273bfa5-6457-43e7-a4b8-0ce25a3dbc93)

**Comment by datguypiko** [comment]
Which version of firefox are you using and did you install latest version?

https://github.com/datguypiko/Firefox-Mod-Blur/releases/tag/v2.14

**Comment by B1ack3ye** [comment]
I have the same problem on Linux.
Latest release.
Arch | Hyprland
![20241127_05h14m25s_grim](https://github.com/user-attachments/assets/f2c169a9-b143-4312-83b7-06a7d548dd8c)

**Comment by TheMasterOfMadness** [comment]
Same issue on Windows after latest Update
![image](https://github.com/user-attachments/assets/c4594de4-678a-474a-82e8-51615f8f3b0e)

**Comment by Anuneza** [comment]
Excellent! I downloaded version 2.14 from the link you provided and just had to paste the installer.py into the extraction folder and select update :D.

I appreciate the attention, very kind
![Screenshot from 2024-11-27 07-44-56](https://github.com/user-attachments/assets/c43fdafc-4b13-41ca-b15d-cdb0309069be)
