### ISSUE TITLE
laggy animations

### ISSUE THREAD

**Issue by stasrobeiko** [datguypiko/Firefox-Mod-Blur#167]
I used Firefox mod-blur v2.9 before, I had no problems with it, everything was very cool, but when I updated Firefox to version 133, also updated mod-blur to v2.14, I noticed that the animations of the tabs appearing became very jerky and ugly. Is there any way to fix this? I really like this modification, but these lags spoil the impressions a little, compared to what was before

https://github.com/user-attachments/assets/b2a955eb-54b6-421f-ab2a-fabf18c6c0fb

but as soon as I open a private window, the lags disappear

https://github.com/user-attachments/assets/f090b376-9c8b-4272-8ee7-6ae2040202fd

**Comment by datguypiko** [comment]
I cant reproduce it.
Maybe try with using this mod selected_tabs_static_width.css

**Comment by datguypiko** [comment]
One thing I notice that your tabs dont have transition effect. Should increase in width.

**Comment by stasrobeiko** [comment]
> One thing I notice that your tabs dont have transition effect. Should increase in width.

about the transition effect do you mean the increase of the selected tab? I changed this parameter a little, because it is more convenient for me

**Comment by datguypiko** [comment]
here is what it looks like for me.

[Video.webm](https://github.com/user-attachments/assets/3bc541d6-6386-419b-9ce5-7104be035c94)

**Comment by stasrobeiko** [comment]
> here is what it looks like for me. Looking at your video definitely I dont see width transition animation.
> Video.webm

When I reinstalled the mod completely, all the lags disappeared. Then why, when I change the size of the tab, lags appear, because there was no such problem before

https://github.com/user-attachments/assets/e391e9c7-f1eb-4d8d-b0d3-fd7e500905c3

**Comment by stasrobeiko** [comment]
> No idea, changing --firefoxcss-tab-min-width and --firefoxcss-tab-max-width doesnt really affect it in anyway in terms of lag for me.
> 
> Do you change anything else in particular?

sorry, i found out what the problem was, it turns out it's because of the wallpaper mod.. when i disabled it, the lags disappeared

**Comment by datguypiko** [comment]
> > No idea, changing --firefoxcss-tab-min-width and --firefoxcss-tab-max-width doesnt really affect it in anyway in terms of lag for me.
> > Do you change anything else in particular?
> 
> sorry, i found out what the problem was, it turns out it's because of the wallpaper mod.. when i disabled it, the lags disappeared

maybe high resolution image could be slowing it down when loading new tab. Interesting.

**Comment by stasrobeiko** [comment]
> No idea, changing --firefoxcss-tab-min-width and --firefoxcss-tab-max-width doesnt really affect it in anyway in terms of lag for me.
> 
> Do you change anything else in particular?

as far as I remember, there was no such add-on before, but there was the ability to set wallpaper, and there were no lags, but when the ability to set wallpaper appeared as an add-on, then for some reason because of it I got lags, maybe there is another way to set wallpaper, but so that there are no lags?
![image](https://github.com/user-attachments/assets/46599bfa-2eda-4bb5-90e0-840e8bfae2b1)

**Comment by stasrobeiko** [comment]
> > > No idea, changing --firefoxcss-tab-min-width and --firefoxcss-tab-max-width doesnt really affect it in anyway in terms of lag for me.
> > > Do you change anything else in particular?
> > 
> > 
> > sorry, i found out what the problem was, it turns out it's because of the wallpaper mod.. when i disabled it, the lags disappeared
> 
> maybe high resolution image could be slowing it down when loading new tab. Interesting.

I reduced the resolution 3 times, to 720p, but the lags did not disappear, I admit, lags can occur through blur on a new tab

**Comment by stasrobeiko** [comment]
> maybe high resolution image could be slowing it down when loading new tab. Interesting.

I disabled this line and the lags mysteriously disappeared. Is blur really that demanding?
![image](https://github.com/user-attachments/assets/62da1d8f-9b11-4a06-bf1e-6693b879c423)

**Comment by datguypiko** [comment]
yes I was about to say that it could be blur too.

You can simply change wallpaper with this code.

add this to the end of userContent.css 
you will need to put wallpaper in chrome folder. If it's png change `url("wallpaper.jpg")` to `url("wallpaper.png")`

```css
@-moz-document url("about:home"),
url("about:newtab") {

  body {
      background-image: url("wallpaper.jpg") !important;
      background-size: cover !important;
      background-position: center !important;
  }

}

```

**Comment by stasrobeiko** [comment]
> yes I was about to say that it could be blur too which I personally cant reproduce with.
> 
> You can simply change wallpaper with this code.
> 
> add this to the end of userContent.css you will need to put wallpaper in chrome folder. If it's png change `url("wallpaper.jpg")` to `url("wallpaper.png")`
> 
> ```css
> @-moz-document url("about:home"),
> url("about:newtab") {
> 
>   body {
>       background-image: url("wallpaper.jpg") !important;
>       background-size: cover !important;
>       background-position: center !important;
>   }
> 
> }
> ```
> 
> You can remove the wallpaper edition file.

Okay, thanks for your help!
