### ISSUE TITLE
Input bar suddenly hovers over the rest of the tabs.

### ISSUE THREAD

**Issue by michelklaasen** [datguypiko/Firefox-Mod-Blur#169]
So, kind of a funny story, I have been running firefox with this theme just fine recently, until today...

What happened?

I installed arch linux... However, on a different drive? And for some reason, this has affected some windows settings.

I have no idea why and perhaps you could help me out with troubleshooting.

What has changed is that the input bar now hovers over the tab bar. You can see in the top left at the edge that the tabs (some pinned ones) are still visible behind the input bar. I can see the shadows of them change when I change tabs.

![2024_11_28 20h08m04s PC](https://github.com/user-attachments/assets/00d9e497-d6b1-4fc8-b6b6-99a60d84e6d2)

System: 
Windows 11 Pro 22H2
Firefox 133.0
Runs with [betterfox](https://github.com/yokoffing/Betterfox)

If I rename userchrome.css, it reverts to the normal theme, which works, but I don't like that theme so much.

I have windows on my C drive, 1 TB NVME
And I installed arch linux on a 256GB SSD.
I didn't change anything to my windows configuration during the install.

I noticed that some windows settings were changed after installing linux. For instance, my sound device preferences. But, I have no idea why my browser would behave differently. This could not be an issue with firefox mod blur at all, I just thought that it might and perhaps you could help troubleshooting.

**Comment by datguypiko** [comment]
download the latest files 
https://github.com/datguypiko/Firefox-Mod-Blur/releases/tag/v2.14

**Comment by michelklaasen** [comment]
Yep, that's it. It was indeed the firefox update that broke things, not my other OS install or betterfox. Downloaded the latest files and it works again. Thanks.
