### ISSUE TITLE
Don't know if I was do something wrong :(

### ISSUE THREAD

**Issue by HuyHung1408** [datguypiko/Firefox-Mod-Blur#17]
![image](https://user-images.githubusercontent.com/86362423/131251361-817c4486-99b7-4f67-b58b-2bd2e9b727aa.png)
Everything except the word is also black

**Comment by datguypiko** [comment]
Right click anywhere on the top bar and then Customize Toolbar, at the bottom select Dark theme from the list.

**Comment by HuyHung1408** [comment]
ok, thanks, problems solved
