### ISSUE TITLE
Tabs are not displayed

### ISSUE THREAD

**Issue by DIMFLIX-OFFICIAL** [datguypiko/Firefox-Mod-Blur#174]
With the release of firefox version 133.0.3 tabs are no longer displayed.
Below I have attached the styles that I transferred to myself.

![image](https://github.com/user-attachments/assets/a4887316-eba2-49d9-87b9-5974c6b151bd)
![image](https://github.com/user-attachments/assets/a799f51c-76b1-431c-a13a-0ebe0b042f13)

**Comment by datguypiko** [comment]
Update to latest version https://github.com/datguypiko/Firefox-Mod-Blur/releases/tag/v2.14

**Comment by DIMFLIX-OFFICIAL** [comment]
Thanks. What kind of files do you need? So you don't have to drag and drop.

**Comment by DIMFLIX-OFFICIAL** [comment]
Thanks
