### ISSUE TITLE
previous tab shows fully not icon

### ISSUE THREAD

**Issue by RomjanHossain** [datguypiko/Firefox-Mod-Blur#19]
I love this repo btw.
I've implemented all those userChrome and userContent and now it looks awesome. 

https://raw.githubusercontent.com/datguypiko/Firefox-Mod-Blur/master/preview/titlebar.gif

in the `gif` file all the previous tabs only show icons. How can i do this?

**Comment by datguypiko** [comment]
When you right click on tab and pin it, it only shows the icon.
