### ISSUE TITLE
Minimize, maximize and close buttons are too small

### ISSUE THREAD

**Issue by Gabriel-Ricardo** [datguypiko/Firefox-Mod-Blur#22]
![Screenshot_20220719_173656](https://user-images.githubusercontent.com/52942897/179846254-277c170e-40bb-4ed8-b3a7-a304349423fd.png)
how can i increase their size? can you help me please? your theme is amazing

**Comment by datguypiko** [comment]
Haven't tested on different OS but try increasing these values in userChrome.css

```
.titlebar-button > .toolbarbutton-icon {
    width: 15px !important;
    min-width: 15px !important;
   min-height: 15px !important;
    height: 15px !important;
    stroke: none !important;
}
```

If that doesnt work just use "userChrome-NoBlur-WindowsButtonsLeftSide.css" for default OS buttons.
Remove the First yellow option. If there are still issues try playing around or removing the second one too. The red is for which goes after another if you want to reverse the order.

![image](https://user-images.githubusercontent.com/61329159/179850565-64d710dd-c541-4ba0-a7b9-3e82d53beddc.png)

**Comment by datguypiko** [comment]
> ![Screenshot_20220719_173656](https://user-images.githubusercontent.com/52942897/179846254-277c170e-40bb-4ed8-b3a7-a304349423fd.png) how can i increase their size? can you help me please? your theme is amazing

If you still not have been able to fix it let me know. Closing for now as no response.
