### ISSUE TITLE
Firefox menu opening to out of the window

### ISSUE THREAD

**Issue by demirdegerli** [datguypiko/Firefox-Mod-Blur#23]
The menu is opening to the left side like default layout, can this be fixed by tweaking css?
(I'm using Windows 11, the latest stable version of Firefox)
![image](https://user-images.githubusercontent.com/67432156/183507606-e424e34c-c414-451e-8d26-e01f506e6e98.png)

**Comment by datguypiko** [comment]
> The menu is opening to the left side like default layout, can this be fixed by tweaking css? (I'm using Windows 11, the latest stable version of Firefox)

Thanks didnt notice that. Will fix the files. Here at this at the end of the userChrome.css file

`#appMenu-popup {margin-inline: -260px !important;}`

**Comment by demirdegerli** [comment]
Worked, thank you :)
