### ISSUE TITLE
How to reduce the tag bar height, is too high to me

### ISSUE THREAD

**Issue by louisrc3ys** [datguypiko/Firefox-Mod-Blur#24]
<img width="232" alt="2022-09-18_13-59" src="https://user-images.githubusercontent.com/71259902/190888262-8b837514-30ed-43b8-a382-4a3d839b7f8d.png">

**Comment by louisrc3ys** [comment]
/home/louis/Screenshot/shot/2022-09-18_13-59.png

**Comment by datguypiko** [comment]
lower these in userchrome.css
![image](https://user-images.githubusercontent.com/61329159/191371100-c0447093-6aa1-44c3-975c-965743180640.png)

**Comment by louisrc3ys** [comment]
> 

Thanks man, i love this theme,  i will keep to use it
