### ISSUE TITLE
How to remove the redundant material from the address bar?

### ISSUE THREAD

**Issue by vrindavan** [datguypiko/Firefox-Mod-Blur#25]
I love how in chromium browsers you just see the lock icon to understand if the site is HTTP or HTTPS but in Firefox it is just redundant to see the full URL. I want to see just the main URL. Below is the CSS I was using but it is not working anymore after using your files.

```
.urlbar-input-box{
  overflow: clip;
}

#urlbar-input{
  margin-left: calc(var(--urlbar-scheme-size) * -0.76) !important;
}
```

**Comment by datguypiko** [comment]
And here is how you can make it more left
![image](https://user-images.githubusercontent.com/61329159/191992499-389509ae-c134-4376-aa58-e3c2621c2e2b.png)
Add `visibility: collapse;` after opacity and `margin-left: 10px;` in _.urlbar-input-box_ 

```

#nav-bar:not([customizing="true"])
  > #nav-bar-customization-target
  > #urlbar-container:not(:hover)
  > #urlbar:not([focused])
  > #urlbar-input-container
  > #identity-box {
  opacity: 0;
  visibility: collapse;
}

.urlbar-input-box{
  overflow: clip;
  margin-left: 10px;
}

#urlbar-input{
  margin-left: calc(var(--urlbar-scheme-size) * -0.72) !important;
}


```

and if you want even more left do the same for (add  visibility: collapse;); 

```
#nav-bar:not([customizing="true"])
  > #nav-bar-customization-target
  > #urlbar-container:not(:hover)
  > #urlbar:not([focused])
  > #urlbar-input-container
  > #tracking-protection-icon-container {
  opacity: 0;
 visibility: collapse;
}
```

**Comment by vrindavan** [comment]
This is just great! Thanks a lot.
