### ISSUE TITLE
Right click menu buttons (back / forward / reload / star) look weird

### ISSUE THREAD

**Issue by xfzv** [datguypiko/Firefox-Mod-Blur#35]
![01](https://user-images.githubusercontent.com/78810647/208463145-befa5de7-f99e-4a86-a094-f3a0db328056.png)
![02](https://user-images.githubusercontent.com/78810647/208463148-70adad18-4fc3-48e7-921f-c281fc0ff17a.png)
![03](https://user-images.githubusercontent.com/78810647/208463151-ab622cea-7460-45f4-8e52-fab518b9fa5c.png)
![04](https://user-images.githubusercontent.com/78810647/208463154-3ae6afdb-e450-4b6c-8904-1a819334f71f.png)

- Linux
- Firefox 108.0.1
- Firefox-Mod-Blur v2.2.1

**Comment by datguypiko** [comment]
Firefox has different code on linux so most stuff will probably be broken. Maybe in the future I will make it work.

Anyway I installed the manjaro to test it and fixed it with this code:

Replace in userChrome.css from line 512 to line 525

```css
menupopup
  > :-moz-any(menu[_moz-menuactive="true"], menuitem[_moz-menuactive="true"]) {
  background-color: color-mix(in srgb, currentColor 9%, transparent) !important;
     appearance: none !important;
}

#context-navigation
  > .menuitem-iconic[_moz-menuactive="true"] {
  border-radius: var(--toolbarbutton-border-radius) !important;
  background-color: var(--button-hover-bgcolor) !important;
  appearance: none !important;
}

```
