### ISSUE TITLE
ublock-icon-change.css no longer working?

### ISSUE THREAD

**Issue by xfzv** [datguypiko/Firefox-Mod-Blur#36]
![image](https://user-images.githubusercontent.com/78810647/208464242-3760dd56-3011-4513-a72c-cd195d3ee56d.png)

- Linux
- Firefox 108.0.1
- Fresh profile

`ublock-icon-change.css` used to work before, not sure what happened. Can reproduce with my main profile.

- `tree ~/.mozilla/firefox/vri2vvdf.Test/chrome`:

```
/home/xfzv/.mozilla/firefox/vri2vvdf.Test/chrome
├── Firefox-Mod-Blur-chrome.css
├── Firefox-Mod-Blur-content.css
├── image
│   ├── about-logo-private-changed.png
│   ├── browser-firefox.svg
│   ├── files.svg
│   ├── Firefox_2019.svg
│   ├── firefox.png
│   ├── firefox.svg
│   ├── firefoxx.png
│   ├── left-arrow.svg
│   ├── noise-512x512.png
│   ├── right-arrow.svg
│   ├── search-glass.svg
│   ├── spill-main.svg
│   ├── spill.svg
│   ├── stack.svg
│   ├── wallpaper_2560x140.jpg
│   ├── wallpaper2.jpg
│   ├── wallpaper3_3840x2160.jpg
│   ├── wallpaper4_3840x2157.png
│   ├── wallpaper_7680x4320.jpg
│   └── wallpaper.jpg
├── privacy_blur_email_in_main_menu.css
├── ublock-icon-change.css
├── userChrome.css
└── userContent.css

1 directory, 26 files
```

Note that `privacy_blur_email_in_main_menu.css` works just fine:

![image](https://user-images.githubusercontent.com/78810647/208464800-3eb05475-3d4d-4178-9f4b-dfddd777d9e8.png)

and so do the other modifications:

![image](https://user-images.githubusercontent.com/78810647/208465167-8686a412-c25f-488d-83c1-65cc7ceeabbf.png)

**Comment by datguypiko** [comment]
Thanks for report. They changed the ID name so need an update.

Here I fixed it, re download the file https://github.com/datguypiko/Firefox-Mod-Blur/tree/master/EXTRA%20MODS/Icon%20mods.
