### ISSUE TITLE
Button issues

### ISSUE THREAD

**Issue by xWqNN** [datguypiko/Firefox-Mod-Blur#38]
![image](https://user-images.githubusercontent.com/60393554/210875478-c9d980da-cb2b-4776-b88b-681af2a9b110.png)
![image](https://user-images.githubusercontent.com/60393554/210875499-0f2c7219-2621-428a-948a-3626f32d904c.png)

I can't see back and forward icon, owerflow icon is on left corner but in settings it's on right corner how can i fix those?

**Comment by datguypiko** [comment]
looks like you haven't downloaded the image folder.

**Comment by datguypiko** [comment]
No response.
