### ISSUE TITLE
[FR] Add separate files for Linux

### ISSUE THREAD

**Issue by xfzv** [datguypiko/Firefox-Mod-Blur#40]
[Your workaround](https://github.com/datguypiko/Firefox-Mod-Blur/issues/35#issuecomment-1358071726) for #35 is valid, but it doesn't integrate well with my workflow.

I'm using [chezmoi](https://github.com/twpayne/chezmoi) to manage my dotfiles. I'm handling both `userChrome.css` (and the other directories/files too) from this repository as [external files](https://www.chezmoi.io/reference/special-files-and-directories/chezmoiexternal-format/).

As a result, for now I have to edit `userChrome.css` myself when my "externals" are updated (see [`-R, --refresh-externals`](https://www.chezmoi.io/reference/command-line-flags/global/#-r-refresh-externals-value)).

I tried writing a script with `sed` that runs every time I update my dotfiles but it doesn't work as expected for various reasons and it's an horrible hack anyway.

Would you consider adding separate variants for Linux with specific fixes which can be used as is? I have yet to find other issues apart from #35 but there might be some more in the future.

Thanks.

**Comment by datguypiko** [comment]
I added it here but I doubt I will maintain it for linux as even different distros have different problems so I would be trying to fix it blindly by braking for others.
https://github.com/datguypiko/Firefox-Mod-Blur/tree/master/old/linux
