### ISSUE TITLE
Changing tab colors

### ISSUE THREAD

**Issue by Alyei** [datguypiko/Firefox-Mod-Blur#41]
Hello!

I want to change the colors of active/background tabs, as I find it jarring that the background tabs on a dark background are highlighted, while the active one almost melds with the background. I think it should be the other way around.

So I've switched the values for `--firefoxcss-tab-bg-color` and `--firefoxcss-tab-active-bg-color` in `userChrome.css`. However, that does not seem to accomplish anything. The values further down in the file at around line 350 have the proper variables set for the background-color property.

Is there something I'm missing?

Thank you for the repo, by the way - I love this!

**Comment by datguypiko** [comment]
You can just set them any color you want.
like 

```css
--firefoxcss-tab-bg-color: hsl(240, 2%, 26%);
  --firefoxcss-tab-hover-bg-color: hsl(240, 2%, 28%);
  --firefoxcss-tab-active-bg-color: hsl(240, 2%, 35%);
```

**Comment by Alyei** [comment]
That's exactly what I did, to no avail. However, I also cannot imagine it functioning any other way. I'll play around some more and try to find what exactly I'm messing up.

Thank you for your help!
