### ISSUE TITLE
[FR] Mod to hide tab bar

### ISSUE THREAD

**Issue by Bahnschrift** [datguypiko/Firefox-Mod-Blur#44]
It would be helpful to have this so that the tab bar can be replaced with a vertical tab extension, such as [tree style tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/) with a custom theme.

I've had a bit of a look at implementing this myself, but I always end up either also hiding the window controls, or hiding tabs but not the space they occupy (leaving a blank bar).

**Comment by datguypiko** [comment]
Try adding this 

```css
#titlebar {
  visibility: collapse !important;
}
```

**Comment by Bahnschrift** [comment]
Perfect. Thank you!
