### ISSUE TITLE
URL bar goes umlimit expand

### ISSUE THREAD

**Issue by JuenTingShie** [datguypiko/Firefox-Mod-Blur#5]
Hi, I just found that if you keep switching layout style,  One Line  mode's URL bar will expand height unlimited...I'm ver. 75
![圖片](https://user-images.githubusercontent.com/31978492/81789647-ddca0b80-9536-11ea-8980-7f1dc2d774ba.png)

**Comment by datguypiko** [comment]
Yea, I had it fixed at one point but it started again, you need to restart Firefox for it to stick to the selected size, it just happens when you are changing it. If anyone will find the problem let me know.

**Comment by datguypiko** [comment]
Fixed in proton version .css file.
