### ISSUE TITLE
change background wallpaper ?

### ISSUE THREAD

**Issue by SaiyajinK** [datguypiko/Firefox-Mod-Blur#50]
Hi,

I discover your mod for mozilla... simply incredible ! it's clean, it's simple, nice work!

I had good success installing it on **Firefox 110.0.1** !

However, I can't put a personalized wallpaper either at startup or when opening a new tab?

![LPAlJVy2Zs](https://user-images.githubusercontent.com/105972098/224070077-0906ccc5-67fe-4205-99ae-e20ddb60b8e8.png)

Can you tell me how to do it because I can't.

Thanks for your feedback !

**Comment by datguypiko** [comment]
Try downloading one of the wallpaper styles and "wallpaper" folder from here https://github.com/datguypiko/Firefox-Mod-Blur/tree/master/EXTRA%20THEMES/Wallpaper%20Edition%20Files
and put it inside of the chrome folder where userChrome.css sits. Then just have your own picture named "wallpaper.jpg" inside wallpaper folder.

**Comment by SaiyajinK** [comment]
@datguypiko works fine thank you ! 👍 

![10kZdJAbCe](https://user-images.githubusercontent.com/105972098/224095933-a3ccbe8e-fc66-4983-ac78-067e5f64264d.png)

-

where can i find this particular wallpaper ? (because it is not in the wallpaper folder)

![firefox_MxL4ePlVPO](https://user-images.githubusercontent.com/105972098/224100127-f46443f8-9c23-4101-8c95-c8db030ca7b9.png)

**Comment by SaiyajinK** [comment]
I created blurred versions of the firefox logo (blue and classic)

![Sans titre-2](https://user-images.githubusercontent.com/105972098/224153455-c9190433-ab22-4616-80b7-7445025dd27d.png)


Available here : 
[Wallpapers Firefox (Firefox-Mod-Blur).zip](https://github.com/datguypiko/Firefox-Mod-Blur/files/10935901/Wallpapers.Firefox.Firefox-Mod-Blur.zip)

++
