### ISSUE TITLE
Icons too big.

### ISSUE THREAD

**Issue by zcresh** [datguypiko/Firefox-Mod-Blur#53]
The top active extensions are too big meanwhile the bottom non-active are the right size.

Currently using: [Style 2 of the Cleaner extension menu](https://github.com/datguypiko/Firefox-Mod-Blur/blob/master/EXTRA%20MODS/Compact%20extensions%20menu/Style%202/cleaner_extensions_menu.css)

![Issue.](https://i.imgur.com/LsIIn1K.png)

**Comment by datguypiko** [comment]
Get the files from here:
https://github.com/datguypiko/Firefox-Mod-Blur/tree/master/For%20Firefox%20version%20113.x/EXTRA%20MODS/Compact%20extensions%20menu

**Comment by zcresh** [comment]
Thank you

**Comment by zcresh** [comment]
Thank you
