### ISSUE TITLE
Weird looking min/max/close buttons

### ISSUE THREAD

**Issue by WadeRK** [datguypiko/Firefox-Mod-Blur#61]
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/86435212/ab65c954-ff16-4fa1-b911-66b6460431d0)
This is pretty much what my min/max/close buttons look like. Any idea how to fix them & make them look like the macOS buttons? And if the macOS buttons aren't possible then just the stock Windows buttons. I'm using MicaForEveryone effects.

Thanks in advance.

**Comment by WadeRK** [comment]
I just realized it's because I'm using a custom Windows theme. Is there absolutely no work around here?

**Comment by datguypiko** [comment]
There isn't. Only default buttons. Even default buttons are hidden most of the time because the way micaforEveryone works and the things Firefox needs to have enabled creates a second copy of the buttons on top with no way to edit or move. Maybe one day they will fix it.
