### ISSUE TITLE
Wallpaper not working

### ISSUE THREAD

**Issue by Mapl3Man** [datguypiko/Firefox-Mod-Blur#63]
I have a wallpaper folder in my chrome folder with a wallpaper.jpg inside but it's still not showing up.

**Comment by datguypiko** [comment]
You need the style css file from here too.
https://github.com/datguypiko/Firefox-Mod-Blur/tree/master/EXTRA%20THEMES/Wallpaper%20Edition%20Files

**Comment by Mapl3Man** [comment]
Thank you it works now. Also how can I make so the min-max-close mac OS style buttons are always colourful not just when I bring my cursor close?

**Comment by datguypiko** [comment]
remove these lines in min-max-close.css file 

![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/32ad0bf4-6590-4499-9b6f-ad5e25f45393)

**Comment by Mapl3Man** [comment]
Thank you so much everything works perfectly now :)
