### ISSUE TITLE
Icons not appearing

### ISSUE THREAD

**Issue by Mxkusei** [datguypiko/Firefox-Mod-Blur#65]
The menu icon and the forward/back buttons aren't showing, the buttons are still working it's just the icons are gone.
![Screenshot 2023-07-16 150120](https://github.com/datguypiko/Firefox-Mod-Blur/assets/71773791/dedbc457-bfab-4c1e-8ed0-9081d21108b7)

**Comment by datguypiko** [comment]
Read [installation instructions](https://github.com/datguypiko/Firefox-Mod-Blur#wrench-installation). Put "image" folder where userChrome.css sits.
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/1c765147-5611-4cec-acfd-e79a13e1651b)

**Comment by Mxkusei** [comment]
Solved it, apparently when I copied the images folder over the files inside the folder didn't copy over either.
