### ISSUE TITLE
All text colors are black

### ISSUE THREAD

**Issue by StannArax** [datguypiko/Firefox-Mod-Blur#66]
All text colors are black and the theme is dark. It does not matter light theme or dark theme, text colors are always dark.

**Comment by datguypiko** [comment]
OS ? Firefox Version? Where did you set it to dark, in OS or firefox?

**Comment by StannArax** [comment]
Windows 11, Firefox 115.0.2 (64-bit), dark mode on Firefox.

**Comment by datguypiko** [comment]
I have the same and white windows theme with dark firefox shows normal text.
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/556f1708-0261-492b-b0ea-d5e29f199423)

**Comment by datguypiko** [comment]
> 

I dont have the white theme right now maybe one day.

**Comment by CorWilson** [comment]
Firefox has a Dark Theme setting in their main Settings menu. Not sure when it was added, but you likely should clarify @datguypiko to use the Dark theme in the Themes menu. I was wondering why my font was all too dark, too, until I saw this issue.
