### ISSUE TITLE
Light and Dark Modes

### ISSUE THREAD

**Issue by StannArax** [datguypiko/Firefox-Mod-Blur#67]
I accidentally closed my previous topic. Is there any way to use the custom theme on light mode? dark texts and white backgrounds.

**Comment by datguypiko** [comment]
You can by changing colors inside the userChrome.css file. But I dont have the white theme right now maybe one day.

If you want I could make one in few days.

**Comment by StannArax** [comment]
I love to use light mode, not at all apps like Discord but I'll be so happy if I use your theme in light mode. Cuz It's actually what I want on a web browser. If can, can you add a bit more customization like Light mode and some tabs modifications? Tab mods like https://github.com/vinceliuice/WhiteSur-firefox-theme . And that's just a request by myself. Your repo have a lot of customizations. Thank you for all of this options.

**Comment by datguypiko** [comment]
> 

I will let you know when I'm done. You can leave this open.

**Comment by datguypiko** [comment]
Here how it looks right now. Will need to rewrite some other files and new tab to work normally. 
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/14b9f7ab-b8d6-4fe2-9c1e-deb586a93cb9)

**Comment by StannArax** [comment]
Really so beautiful. That's what I wanna see in a browser literally. Thank you for your work and sorry for late answering. Can I download it now?

**Comment by StannArax** [comment]
Okay and thank you for your work again.

**Comment by datguypiko** [comment]
You can download it here https://github.com/datguypiko/Firefox-Mod-Blur/releases/tag/2.6

Read [Installation](https://github.com/datguypiko/Firefox-Mod-Blur/tree/master#wrench-installation) on how to toggle between Dark and Light themes.

If you want some tab modifications you need to be more specific on what you mean by that and which exactly you want.

**Comment by StannArax** [comment]
Thank you so much! And about tabs,
https://raw.githubusercontent.com/vinceliuice/WhiteSur-gtk-theme/pictures/pictures/firefox.svg
I really love Monterey and alt styles on the image. 
If you need some help, I hope https://github.com/vinceliuice/WhiteSur-firefox-theme link will help you a bit.

**Comment by datguypiko** [comment]
> Thank you so much! And about tabs, https://raw.githubusercontent.com/vinceliuice/WhiteSur-gtk-theme/pictures/pictures/firefox.svg I really love Monterey and alt styles on the image. If you need some help, I hope https://github.com/vinceliuice/WhiteSur-firefox-theme link will help you a bit.

I will release one liner maybe in the future but no plans for now.

**Comment by StannArax** [comment]
Okay, no problem. You did everything for modification Firefox. And also you made it most beautiful web browser...
