### ISSUE TITLE
Overlap between min-max-close and unified-extensions buttons

### ISSUE THREAD

**Issue by CleanerThanRotom-W** [datguypiko/Firefox-Mod-Blur#68]
Per title, screenshot provided:

![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/98265798/e8b6ebde-2228-4ef6-934b-8f1acf6b691e)

EDIT: Overlap is also partially noticeable when the Menu icon is on the right.

**Comment by CleanerThanRotom-W** [comment]
> Operating system?

Windows 11, latest Librewolf

**Comment by datguypiko** [comment]
> > Operating system?
> 
> Windows 11, latest Librewolf

I fixed it. Should be fine now. Redownload the userChrome.css and [min-max-close](https://github.com/datguypiko/Firefox-Mod-Blur/tree/master/EXTRA%20MODS/Min-max-close%20window%20buttons/Right%20side%20default%20system%20buttons/MenuButtonsOnLeft) file
