### ISSUE TITLE
[help] make inactive tabs blacker ?

### ISSUE THREAD

**Issue by SaiyajinK** [datguypiko/Firefox-Mod-Blur#71]
Hi,
the mod works relatively well, however I would like to be able to better distinguish between active and non-active tabs.

How to make inactive tabs blacker?

https://github.com/datguypiko/Firefox-Mod-Blur/assets/105972098/5db506c8-1475-4d44-83ea-2b78ec048b13

thx 👍🏻

**Comment by datguypiko** [comment]
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/3d7501ee-97cb-4834-9354-0cee42553113)
Edit acrylic_micaforeveryone file. You can write your own colors there or change 'currentColor' to 'field' and increase or decrease the %.

Download the latest version if you have old files.

**Comment by SaiyajinK** [comment]
@datguypiko I downloaded the latest version (2.6.3)
I edited the lines with basic random colors, restarted firefox but the edits don't work

https://github.com/datguypiko/Firefox-Mod-Blur/assets/105972098/c8741665-162e-4e8f-8d27-a0a4c40742fa

**Comment by SaiyajinK** [comment]
@datguypiko thanks for the tip it's much better now 

https://github.com/datguypiko/Firefox-Mod-Blur/assets/105972098/48523794-f258-47db-b200-9f2edb4c7a33

💯

**Comment by datguypiko** [comment]
Yeah I changed the active tab to darker color.
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/cd66b155-071c-405b-a082-26b89c67b7fd)

**Comment by SaiyajinK** [comment]
@datguypiko I also changed the hover color of the tabs :

`> acrylic_micaforeveryone.css > line 167`

`background-color: hsl(240, 6%, 30%, 0.20) !important;`

https://github.com/datguypiko/Firefox-Mod-Blur/assets/105972098/16d8e8e6-320c-4ed3-a0ac-815e0126191f

ou en ajoutant une nouvelle variable :

`--firefoxcss-unactive-tab-bg-color-hover`

`background-color: var(--firefoxcss-unactive-tab-bg-color-hover)`

you can close the ticket thank you!
