### ISSUE TITLE
help, v2.7/117.0 issues

### ISSUE THREAD

**Issue by SaiyajinK** [datguypiko/Firefox-Mod-Blur#75]
Hi,
I just upgraded to version 2.7 for FF 117.0 but I noticed several problems:

1- Mica is no longer transparent
2- unable to resize my Firefox window
3- the close, enlarge, minimize buttons are no longer visible except close button on hover

https://github.com/datguypiko/Firefox-Mod-Blur/assets/105972098/261b0591-4108-4a36-b7d5-3bfc1d7e50b4

fix please? :)

**Comment by datguypiko** [comment]
mica no longer supported for firefox 117 and up.
read more here if you want to keep using it with older version 
https://github.com/datguypiko/Firefox-Mod-Blur#wrench-micaforeveryone-installation

Basically you need to use v115 ESR edition of firefox.

**Comment by SaiyajinK** [comment]
@datguypiko everything is good with the esr version thank you! :)

**Comment by datguypiko** [comment]
> @datguypiko everything is good with the esr version thank you! :)

If you want something fixed from ESR version let me know. You can create a new issue for that.

**Comment by SaiyajinK** [comment]
@datguypiko no problem, for the moment everything is ok but I will not fail to let you know if necessary thank you!
