### ISSUE TITLE
New store for FirefoxCSS themes

### ISSUE THREAD

**Issue by Neikon** [datguypiko/Firefox-Mod-Blur#8]
Hi, I don't know how to contact you so I'm using this.

We are creating a website where to collect firefox themes. we have included yours by linking to this github.

I invite you to add/change/remove any information we have added to our website. I hope you like the initiative and that in the future you will send us more themes.

here are the links:
web: https://firefoxcss-store.github.io/
repo: https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io

Regards :)

**Comment by datguypiko** [comment]
Looks cool. Thanks!
