### ISSUE TITLE
Tabs on top but OS min/max/close buttons cut off "new tab" button.

### ISSUE THREAD

**Issue by sillonar** [datguypiko/Firefox-Mod-Blur#82]
Just wanna say I've looked through the discussions and didn't see anything. I'm not entirely sure how to navigate GitHub and I'm brain dead when it comes to reading .css files so I'd like to know if it's possible and if so, how to prevent "new tab" button from overlapping the min/max/close buttons on the right side. Thank you.

**Comment by ryannmahajan** [comment]
Look at https://github.com/datguypiko/Firefox-Mod-Blur/issues/69 . The answer at the end should work for you.

**Comment by datguypiko** [comment]
Just remove the code from line 752 to 837 in UserChrome.css or just do what ryannmahajan said if you want to maintain the custom buttons.

**Comment by sillonar** [comment]
Thank you @ryannmahajan and @datguypiko for linking me to a fix.
