### ISSUE TITLE
Mercury - Min/Max/Close buttons & Search bar issue

### ISSUE THREAD

**Issue by Scarlaid** [datguypiko/Firefox-Mod-Blur#88]
There are currently 2 issues with my current use of this theme:
- The Min/Max/Close buttons' color doesn't match, the border is clearly seen
- Search Bar being unaligned to the right side, with and without the container
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/90851437/b2d81bae-c6fb-4249-bb48-c1713be3978e)
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/90851437/a6d3c0b3-9f74-4ece-beed-0b605181e555)

However, I have no issue in Firefox Nightly
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/90851437/e27a35cb-178d-47ac-9aec-035115095ebb)

If needed, this is the [browser](https://thorium.rocks/mercury)

**Comment by datguypiko** [comment]
Looks fine to me with the latest version.
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/f2cbf4c4-8a4f-4224-ab23-5955b68bda63)

![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/05d71d3b-bc1a-40ad-a4fb-27db5d8d7eca)
