### ISSUE TITLE
A few buttons are mising

### ISSUE THREAD

**Issue by F3R96** [datguypiko/Firefox-Mod-Blur#9]
![Screenshot (20210202-003221)](https://user-images.githubusercontent.com/78397863/106549579-07c1c480-64f0-11eb-8dc7-e68bc50e472a.jpg)

**Comment by datguypiko** [comment]
Did you download the image folder and put it in the same place where your css file sits? I dont have mac to test it but if you already have image folder you can solve it by opening the file, searching for "Icons" and removing these lines for old icons.
`list-style-image: url(image/Fx-Browser-icon-oneColor-white.png) !important;
list-style-image: url(image/fire-2-32.ico) !important;
list-style-image: url(image/folder.svg) !important;
list-style-image: url(image/right-arrow.svg) !important;
list-style-image: url(image/left-arrow.svg) !important;
`

**Comment by F3R96** [comment]
> 
> 
> Did you download the image folder and put it in the same place where your css file sits? I dont have mac to test it but if you already have image folder you can solve it by opening the file, searching for "Icons" and removing these lines for old icons.
> 
> `list-style-image: url(image/Fx-Browser-icon-oneColor-white.png) !important;`
> 
> `list-style-image: url(image/fire-2-32.ico) !important;`
> 
> `list-style-image: url(image/folder.svg) !important;`
> 
> `list-style-image: url(image/right-arrow.svg) !important;`
> 
> `list-style-image: url(image/left-arrow.svg) !important;`

Sorry, I alredy fix it haha. I didn't copy everything on the chrome folder, I was missing the image one.
by the way, it's windows with mac os theme 
anyway thanks for this awesome look on my firefox! You rock dude!

**Comment by datguypiko** [comment]
Oh wow didn't know you can make it look like that. Thanks! ^^
