### ISSUE TITLE
[Feature]: Requesting some features.

### ISSUE THREAD

**Issue by niksingh710** [datguypiko/Firefox-Mod-Blur#90]
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/60490474/b83b432e-f947-40a4-b473-dd5a67989e53)
unable to figure out a way to get this blurred.

is there any way to change the colors ? i mean i use pywalfox extension that provide me colors from wallpaper i would like to have those colors ..... it work with default firefox without any theming.
So just curious how can i do that in this theme.

![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/60490474/da96d13e-390f-4a37-b8c8-c2ce08d8d056)
how to make this transparent also?

and in last is there any plans for adding sideberry to have a tabs in side with child and parent tree structure?

**Comment by datguypiko** [comment]
For transparent search change the `--firefoxcss-url-breakout-bar-bg-color` value in userChrome.css. Something like this `hsla(240, 2%, 13%, 0.8);`.

<hr/>

Sidebery works fine (I only tested on windows) just hide the tabs bar with my mod file which you can find [here](https://github.com/datguypiko/Firefox-Mod-Blur/tree/master/EXTRA%20MODS/Tabs%20Bar%20Mods/Hide%20tabs%20bar%20for%20vertical%20tabs).


<hr/>

I dont use Linux so I dont know how blur works there.

You could try adding "backdrop-filter: blur(12px) !important;" to the elements you are trying to blur.

So maybe smthing like this:
```css
#main-window #navigator-toolbox {
   background-image: none !important;
   backdrop-filter: blur(12px) !important;
}
```

**Comment by niksingh710** [comment]
@datguypiko 
yeah so i am unable to get the blur working. also tried force enabling backdrop filter in `about:config` but nothing worked.

one thing i noticed that if i use `filter` instead of backdrop then all the elements like url and extension icons all those get's blurred.

For sideberry i mean if there will be sideberry css to integrate it in a more seamless manner with hover option instead of it being like visible always as i used to use it in hover mode in my previous config.


i get the part that pywalfox would not make sense for you on windows.
how can i make firefox use the default colors instead of the grey one defined in root variables?

**Comment by niksingh710** [comment]
Thanks ig now this can be closed
