### ISSUE TITLE
Search bar in new page not transparent

### ISSUE THREAD

**Issue by qunp1** [datguypiko/Firefox-Mod-Blur#99]
the search bar in new page all of a sudden lost its transparency 

![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/150928288/b77fe244-d39a-4198-a98c-106a94b73b16)

its still transparent in private windows new page

![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/150928288/b9371d2d-1f09-433e-a5d4-13cb578afcf0)

**Comment by qunp1** [comment]
btw other elements work perfectly fine

![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/150928288/9a382301-f97c-4daa-afff-acd2bd63037e)

![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/150928288/0f38709b-945a-468c-9101-7e6dbd5e5d2c)

**Comment by datguypiko** [comment]
works fine for me 
![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/784616ae-906d-4dff-a6de-6de2edcafaa2)

**Comment by qunp1** [comment]
it got fixed after refreshing Firefox, idk what was the problem
